spring.application.name=acente-yonetim
spring.datasource.url=jdbc:postgresql://localhost:5432/acente
spring.datasource.username=acente_yonetim
spring.datasource.password=AcenteTest2026
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true